---
sudo: required
language: python

addons:
  apt:
    packages:
      - docker-ce

install:
  - pip install ome-ansible-molecule-dependencies

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
