---
# tasks file for cadvisor

- name: cadvisor | download
  become: yes
  get_url:
    url: "{{ cadvisor_url }}/{{ cadvisor_version }}/cadvisor"
    checksum: "sha256:{{ cadvisor_checksum }}"
    dest: "/usr/local/bin/cadvisor"
    force: no
    mode: u=rwx,g=rx,o=rx

- name: cadvisor | server systemd service
  become: yes
  template:
    dest: /etc/systemd/system/cadvisor.service
    src: systemd-system-cadvisor-service.j2
  notify:
  - reload systemd
  - restart cadvisor

# Flush handlers to ensure systemd is reloaded
- name: cadvisor | flush systemd handlers
  meta: flush_handlers

- name: cadvisor | enable and start server systemd
  become: yes
  service:
    enabled: yes
    name: cadvisor.service
    state: started
